theme: jekyll-theme-minimal
title: Micha Birklbauer
description: GitHub Page of Micha Birklbauer
logo: https://raw.githubusercontent.com/michabirklbauer/projects/master/avatar.jpg
show_downloads: false
